version: "3.9"
services:
  cleex_redis_dev:
    image: redis:7.2.1-alpine
    container_name: redis_cleex_dev
    restart: always
    command: --port 5375
    expose:
      - 5375

  cleex_app_dev:
    image: cleex_app_dev
    container_name: cleex_app_dev
    build: ./
    command: uvicorn app.main:app --reload --proxy-headers --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "5917:8000"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/files
      - logs:/code/logs
    stdin_open: True
    tty: True
    env_file:
      - .env
    depends_on:
      - cleex_redis_dev

volumes:
  static_volume:
  media_volume:
  logs: